In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
upload=files.upload()

Saving Disease_symptom_and_patient_profile_dataset.csv to Disease_symptom_and_patient_profile_dataset.csv

In [ ]:
data=pd.read_csv('Disease_symptom_and_patient_profile_dataset.csv')

In [ ]:
data

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,19,Female,Low,Normal,Positive
1,Common Cold,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
2,Eczema,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
3,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
...,...,...,...,...,...,...,...,...,...,...
344,Stroke,Yes,No,Yes,No,80,Female,High,High,Positive
345,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
346,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
347,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive
348,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive

In [ ]:
# Count samples per disease
disease_counts = data['Disease'].value_counts()

# Select diseases having >= 25 samples
valid_diseases = disease_counts[disease_counts >= 10].index

# Filter dataset
data = data[data['Disease'].isin(valid_diseases)]

In [ ]:
disease_counts.unique()

array([23, 16, 14, 10,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
print(data['Disease'].value_counts(normalize=True))

Disease
Asthma          0.277108
Stroke          0.192771
Osteoporosis    0.168675
Diabetes        0.120482
Migraine        0.120482
Hypertension    0.120482
Name: proportion, dtype: float64

In [ ]:
valid_diseases

Index(['Asthma', 'Stroke', 'Osteoporosis', 'Diabetes', 'Hypertension',
       'Migraine'],
      dtype='object', name='Disease')

In [ ]:
data

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
3,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
10,Asthma,Yes,No,No,Yes,28,Male,High,Normal,Positive
14,Diabetes,No,No,No,No,29,Male,Low,Normal,Negative
20,Stroke,Yes,Yes,Yes,Yes,29,Female,Normal,Normal,Positive
...,...,...,...,...,...,...,...,...,...,...
344,Stroke,Yes,No,Yes,No,80,Female,High,High,Positive
345,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
346,Stroke,Yes,No,Yes,No,85,Male,High,High,Positive
347,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive
348,Stroke,Yes,No,Yes,No,90,Female,High,High,Positive

In [ ]:
print(data['Disease'].value_counts())

Disease
Asthma          23
Stroke          16
Osteoporosis    14
Diabetes        10
Migraine        10
Hypertension    10
Name: count, dtype: int64

In [ ]:
x=data.drop('Disease',axis=1)
y=data['Disease']

In [ ]:
x

,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
3,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
10,Yes,No,No,Yes,28,Male,High,Normal,Positive
14,No,No,No,No,29,Male,Low,Normal,Negative
20,Yes,Yes,Yes,Yes,29,Female,Normal,Normal,Positive
...,...,...,...,...,...,...,...,...,...
344,Yes,No,Yes,No,80,Female,High,High,Positive
345,Yes,No,Yes,No,85,Male,High,High,Positive
346,Yes,No,Yes,No,85,Male,High,High,Positive
347,Yes,No,Yes,No,90,Female,High,High,Positive
348,Yes,No,Yes,No,90,Female,High,High,Positive

In [ ]:
print("Rows:", data.shape[0])
print("Features:", data.shape[1])

Rows: 83
Features: 10

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
y

array([0, 0, 0, 1, 5, 3, 3, 0, 0, 0, 0, 4, 3, 0, 0, 0, 0, 2, 0, 0, 3, 3,
       4, 5, 1, 3, 1, 0, 0, 0, 0, 0, 0, 3, 5, 1, 3, 5, 0, 0, 1, 1, 2, 4,
       2, 1, 2, 0, 5, 2, 1, 2, 3, 4, 2, 4, 4, 4, 4, 4, 4, 4, 0, 2, 2, 2,
       4, 1, 5, 5, 1, 4, 5, 4, 3, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
print(le.classes_)

['Asthma' 'Diabetes' 'Hypertension' 'Migraine' 'Osteoporosis' 'Stroke']

In [ ]:
x=pd.get_dummies(x).astype(int)

In [ ]:
x

,Age,Fever_No,Fever_Yes,Cough_No,Cough_Yes,Fatigue_No,Fatigue_Yes,Difficulty Breathing_No,Difficulty Breathing_Yes,Gender_Female,Gender_Male,Blood Pressure_High,Blood Pressure_Low,Blood Pressure_Normal,Cholesterol Level_High,Cholesterol Level_Low,Cholesterol Level_Normal,Outcome Variable_Negative,Outcome Variable_Positive
3,25,0,1,0,1,1,0,0,1,0,1,0,0,1,0,0,1,0,1
4,25,0,1,0,1,1,0,0,1,0,1,0,0,1,0,0,1,0,1
10,28,0,1,1,0,1,0,0,1,0,1,1,0,0,0,0,1,0,1
14,29,1,0,1,0,1,0,1,0,0,1,0,1,0,0,0,1,1,0
20,29,0,1,0,1,0,1,0,1,1,0,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,80,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,1
345,85,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1
346,85,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1
347,90,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,1
348,90,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,1

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,
    test_size=0.1,
    stratify=y,
    random_state=42
)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

In [ ]:
from sklearn.svm import SVC
svc_model = SVC(
    kernel='rbf',     # best general-purpose kernel
    C=1.0,            # regularization
    gamma='scale',
    random_state=42
)
svc_model.fit(x_train, y_train)
print("Train Accuracy:", svc_model.score(x_train, y_train))
print("Test Accuracy:", svc_model.score(x_test, y_test))

Train Accuracy: 0.47297297297297297
Test Accuracy: 0.5555555555555556

In [ ]:
model=gb.fit(x_train, y_train)
print("Train:", gb.score(x_train, y_train))
print("Test:", gb.score(x_test, y_test))

Train: 0.9864864864864865
Test: 0.5555555555555556

In [ ]:
y_pred=model.predict(x_test)
print(f"Predicted label for the first test sample: {le.inverse_transform([y_pred[0]])[0]}")
print(f"Actual label for the first test sample: {le.inverse_transform([y_test[0]])[0]}")

Predicted label for the first test sample: Osteoporosis
Actual label for the first test sample: Osteoporosis

In [ ]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
print(acc)

0.5555555555555556

In [ ]:
import numpy as np

new_data_sample = x_test.iloc[0].values.reshape(1, -1)
new_data = model.predict(new_data_sample)
print(f"Predicted label for the first test sample: {le.inverse_transform(new_data)}")

Predicted label for the first test sample: ['Osteoporosis']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(